name: dbtools
description: A simple CLI application for managing the database during developing.
repository: https://github.com/RightBrainPro/dbtools
issue_tracker: https://github.com/RightBrainPro/dbtools/issues
version: 1.1.0

executables:
  dbtools: main

environment:
  sdk: ^3.8.0

dependencies:
  args: ^2.7.0
  convert: ^3.1.2
  path: ^1.9.1
  pointycastle: ^4.0.0
  postgresql2: ^1.7.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
